-- ============================================================================
-- V1__init.sql — schema inicial do BiblioEscola
-- ============================================================================
-- Convencao Flyway: V<numero>__<descricao>.sql (dois underscores)
-- Cada migration nova deve ser uma versao incremental (V2__..., V3__...).
-- Nunca edite uma migration ja aplicada — crie uma nova que altera o schema.
-- ============================================================================

CREATE TABLE usuarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(150) NOT NULL,
    nome        VARCHAR(150) NOT NULL,
    senha_hash  VARCHAR(100) NOT NULL,
    role        VARCHAR(20)  NOT NULL,
    ativo       BOOLEAN      NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX idx_usuarios_email ON usuarios (email);


CREATE TABLE livros (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo                 VARCHAR(200) NOT NULL,
    autor                  VARCHAR(150) NOT NULL,
    isbn                   VARCHAR(20),
    ano                    INTEGER,
    quantidade_exemplares  INTEGER      NOT NULL,
    quantidade_disponivel  INTEGER      NOT NULL,
    version                BIGINT       NOT NULL,
    created_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_livros_isbn UNIQUE (isbn),
    CONSTRAINT ck_livros_qtd_disponivel CHECK (quantidade_disponivel >= 0),
    CONSTRAINT ck_livros_qtd_consistente CHECK (quantidade_disponivel <= quantidade_exemplares)
);
CREATE INDEX idx_livros_titulo ON livros (titulo);
CREATE INDEX idx_livros_autor  ON livros (autor);


CREATE TABLE alunos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula   VARCHAR(30)  NOT NULL,
    nome        VARCHAR(150) NOT NULL,
    turma       VARCHAR(30)  NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_alunos_matricula UNIQUE (matricula)
);
CREATE INDEX idx_alunos_nome  ON alunos (nome);
CREATE INDEX idx_alunos_turma ON alunos (turma);


CREATE TABLE emprestimos (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    livro_id                 BIGINT       NOT NULL,
    aluno_id                 BIGINT       NOT NULL,
    data_emprestimo          DATE         NOT NULL,
    prazo_dias               INTEGER      NOT NULL,
    data_devolucao_prevista  DATE         NOT NULL,
    data_devolucao_efetiva   DATE,
    situacao                 VARCHAR(20)  NOT NULL,
    created_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_emprestimos_livro FOREIGN KEY (livro_id) REFERENCES livros (id),
    CONSTRAINT fk_emprestimos_aluno FOREIGN KEY (aluno_id) REFERENCES alunos (id),
    CONSTRAINT ck_emprestimos_situacao CHECK (situacao IN ('ATIVO', 'DEVOLVIDO')),
    CONSTRAINT ck_emprestimos_prazo CHECK (prazo_dias >= 1)
);
CREATE INDEX idx_emprestimos_situacao                ON emprestimos (situacao);
CREATE INDEX idx_emprestimos_data_devolucao_prevista ON emprestimos (data_devolucao_prevista);
CREATE INDEX idx_emprestimos_aluno_situacao          ON emprestimos (aluno_id, situacao);
CREATE INDEX idx_emprestimos_livro                   ON emprestimos (livro_id);
