-- ============================================================================
-- V4__create_refresh_tokens.sql
-- ============================================================================
-- Refresh tokens opacos para o fluxo access-token-curto + refresh-token-longo.
-- Armazena apenas o hash SHA-256 (token_hash) — o valor puro nunca persiste.
-- ON DELETE CASCADE: remover um usuario remove seus refresh tokens.
-- ============================================================================

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash  VARCHAR(64)  NOT NULL,
    usuario_id  BIGINT       NOT NULL,
    expires_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at  TIMESTAMP(6) WITH TIME ZONE,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_refresh_tokens_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_refresh_tokens_token_hash ON refresh_tokens (token_hash);
CREATE INDEX        idx_refresh_tokens_usuario    ON refresh_tokens (usuario_id);
