-- ============================================================================
-- V5__create_audit_log.sql
-- ============================================================================
-- Trilha de auditoria de eventos de seguranca (login, logout, troca de senha,
-- gestao de usuarios). Registros imutaveis.
-- ============================================================================

CREATE TABLE audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento        VARCHAR(40)  NOT NULL,
    usuario_email VARCHAR(150),
    ip            VARCHAR(45),
    user_agent    VARCHAR(255),
    detalhe       VARCHAR(500),
    ocorrido_em   TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_log_evento        ON audit_log (evento);
CREATE INDEX idx_audit_log_usuario_email ON audit_log (usuario_email);
CREATE INDEX idx_audit_log_ocorrido_em   ON audit_log (ocorrido_em);
