-- ============================================================================
-- V7__create_reservas.sql
-- ============================================================================
-- Reservas de livros feitas pelos alunos. Uma reserva PENDENTE segura um
-- exemplar (o estoque disponivel do livro fica decrementado ate a resolucao).
-- ============================================================================

CREATE TABLE reservas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    livro_id        BIGINT       NOT NULL,
    aluno_id        BIGINT       NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    data_reserva    DATE         NOT NULL,
    data_expiracao  DATE         NOT NULL,
    data_resolucao  TIMESTAMP(6) WITH TIME ZONE,
    emprestimo_id   BIGINT,
    version         BIGINT       NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_reservas_livro      FOREIGN KEY (livro_id)      REFERENCES livros (id),
    CONSTRAINT fk_reservas_aluno      FOREIGN KEY (aluno_id)      REFERENCES alunos (id),
    CONSTRAINT fk_reservas_emprestimo FOREIGN KEY (emprestimo_id) REFERENCES emprestimos (id),
    CONSTRAINT ck_reservas_status
        CHECK (status IN ('PENDENTE', 'CONFIRMADA', 'RECUSADA', 'CANCELADA', 'EXPIRADA'))
);

CREATE INDEX idx_reservas_status ON reservas (status);
CREATE INDEX idx_reservas_aluno  ON reservas (aluno_id);
CREATE INDEX idx_reservas_livro  ON reservas (livro_id);
